# Generated by Django 5.0.7 on 2024-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category_name',
            field=models.ManyToManyField(blank=True, to='nagoyameshi.category', verbose_name='カテゴリ（3つまで選択可）'),
        ),
    ]
