# Generated by Django 5.0.7 on 2024-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'db_table': 'nagoyameshi_category',
            },
        ),
        migrations.CreateModel(
            name='RegularHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=3, verbose_name='定休日')),
                ('holiday_index', models.PositiveIntegerField(null=True, verbose_name='定休日の番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '定休日',
                'verbose_name_plural': '定休日',
                'db_table': 'nagoyameshi_regularholiday',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category_name',
            field=models.ManyToManyField(blank=True, to='nagoyameshi.category', verbose_name='カテゴリ（3つまで選択可）'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='holiday',
            field=models.ManyToManyField(blank=True, to='nagoyameshi.regularholiday', verbose_name='定休日'),
        ),
    ]
