# Generated by Django 5.0.7 on 2024-08-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0002_category_regularholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category_name',
            field=models.ManyToManyField(blank=True, to='nagoyameshi.category', verbose_name='カテゴリ（3つまで選択可）'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='holiday',
            field=models.ManyToManyField(blank=True, to='nagoyameshi.regularholiday', verbose_name='定休日'),
        ),
    ]
