# Generated by Django 5.0.7 on 2024-07-29 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0003_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(message='パスワードは半角8文字以上24文字以内で大文字と記号（.?/-）をそれぞれ1文字以上含めてください', regex='^(?=.*[A-Z])(?=.*[.?/-])[a-zA-Z0-9.?/-]{8,24}$')], verbose_name='パスワード'),
        ),
    ]
